---
{
   "kind": "pipeline",
   "name": "default-amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "mkdir ../build.rbldnsd",
            "cd ../build.rbldnsd",
            "cmake -DNO_IPv6=ON $DRONE_WORKSPACE",
            "make",
            "cd $DRONE_WORKSPACE",
            "mv ../build.rbldnsd/rbldnsd* .",
            "bash -c \"source /venv/bin/activate && robot test/functional/cases\"",
            "bash -c \"source /venv/bin/activate && python3 test/pyunit/tests.py\""
         ],
         "image": "rspamd/rbldnsd:build",
         "name": "test"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "push",
            "pull_request"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "default-arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "mkdir ../build.rbldnsd",
            "cd ../build.rbldnsd",
            "cmake -DNO_IPv6=ON $DRONE_WORKSPACE",
            "make",
            "cd $DRONE_WORKSPACE",
            "mv ../build.rbldnsd/rbldnsd* .",
            "bash -c \"source /venv/bin/activate && robot test/functional/cases\"",
            "bash -c \"source /venv/bin/activate && python3 test/pyunit/tests.py\""
         ],
         "image": "rspamd/rbldnsd:build",
         "name": "test"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "push",
            "pull_request"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "docker-amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "plugins/docker",
         "name": "docker-amd64",
         "settings": {
            "build_args": [
               "TARGETARCH=amd64"
            ],
            "dockerfile": "Dockerfile",
            "dry_run": true,
            "password": {
               "from_secret": "docker_password"
            },
            "tags": [
               "latest-amd64"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "docker-arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "plugins/docker",
         "name": "docker-arm64",
         "settings": {
            "build_args": [
               "TARGETARCH=arm64"
            ],
            "dockerfile": "Dockerfile",
            "dry_run": true,
            "password": {
               "from_secret": "docker_password"
            },
            "tags": [
               "latest-arm64"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "hmac": "0000000000000000000000000000000000000000000000000000000000000000",
   "kind": "signature"
}
...
